### ISSUE TITLE
Add a `cluster info` command to aid users in installation preparation 

### ISSUE THREAD

**Issue by charlieegan3** [jetstack/jsctl#58]
We would like to be able to help users understand what they're running in their clusters prior to onboarding to Jetstack Secure using `jsctl`.

In order to do this, we'd like to have a command that the user can run to get an overview of the Jetstack tooling and cert-manager components in the cluster in YAML.

The proposal is something like this:

```yaml
components: # things 'running' in the cluster which are Jetstack or cert-manager related.
  certManager:
    namespace: cert-manager
    version: v1.9.0
    installationMechanism: Helm
    apiVersion: v1
  venafiEnhancedIssuer:
    namespace: jetstack-secure
    version: v0.0.1
    installationMechanism: Helm

crds: # matching *cert-manager.io or *jetstack.io CRDs
  jetstack.io:
  - installations.operator.jetstack.io
  cert-manager.io:
  - certificaterequests.cert-manager.io   
  - certificates.cert-manager.io
  - challenges.acme.cert-manager.io       
  - clusterissuers.cert-manager.io
  - issuers.cert-manager.io              
  - orders.acme.cert-manager.io

issuers: # a list of all issuers and cluster issuers in the cluster
- kind: VenafiIssuer
  name: my-tpp-issuer
  namespace: my-tpp
- kind: ClusterIssuer
  name: my-ca-issuer

ingresses:
- name: foo
  namespace: foo
  ingressClass: nginx
  issuer: my-tpp-issuer
         
namespaces:
- cert-manager
- jetstack-secure
```

The command might look like this:

```
jsctl cluster info --format=[json|yaml]
```
